### PR TITLE
[update] Add and delete various icons

### LINKED ISSUE #3: Sync device list needs a tablet icon
There is only mobile phone icon now https://github.com/FirefoxUX/photon-icons/blob/master/icons/desktop/device-mobile-16.svg
We should also have a tablet icon.
Those are used in sync device lists, and the sync device list message specifies mobile phone and mobile tablet.

### LINKED ISSUE #30: Add sidebar icon for when the sidebar is on the left
We currently have a sidebar icon that displays a sidebar on the right side of the window. Add an icon that displays the sidebar on the left side of the window.

screen shot 2018-07-12 at 3 22 48 pm

### LINKED ISSUE #31: Add pocket outline icon
See https://bugzilla.mozilla.org/show_bug.cgi?id=1462790

### LINKED ISSUE #36: Add new tracking protection icons
See https://searchfox.org/mozilla-central/source/browser/themes/shared/controlcenter

There's cookies/trackers/slow trackers

### PR DESCRIPTION
**Pull request by nt1m**
Fixes #3 
Fixes #30
Fixes #31
Fixes #36

### CODE REVIEW

**Comment by nt1m** [comment]
@bwinton Can you please review this PR ? Thanks!

**Comment by bwinton** [comment]
Could you run `npm run build`, to optimize the icons? Aside from that, the code looks fine. @shorlander, @bryanbell, or @brassy- should probably review the style of the icons before we merge…

**Comment by nt1m** [comment]
@bwinton These are all directly ported from `m-c`.

Unfortunately, `npm run build` rips out all the license headers, but I can look at this later today.

**Comment by nt1m** [comment]
Just to ease-up UX review:

- The autoplay icons were introduced in bug 1461656, and I believe @bryanbell created them
- The pocket outline icon was introduced in bug 1462790, and was created by @shorlander
- The tablet icon was introduced in bug 1383898 and was created by @brampitoyo
- The policy engine icons were introduced and bug 1485636 and also were created by Bram
- The left sidebar icon is just a flipped version of the right sidebar icon, and it's been introduced in bug 1347543
- The cookie icons were introduced in bug 1484312
- The cryptomining/fingerprinting icons were introduced in bug 1522567

**Pull request merged**
