### PR TITLE
Import icons from Fenix

### PR DESCRIPTION
**Pull request by NotWoods**
Lots of icons have been created for Fenix but not updated here.

### CODE REVIEW

**Comment by bwinton** [comment]
Stephen, Bryan, would one of you please review these icons, and let me know if we should merge them? Thanks!

**Comment by mheubusch** [comment]
@shorlander do we still need the correctly centered icon for cancel-24? If so, it is not in moz central - how do we get it?

**Comment by shorlander** [comment]
It looks like this is adding one iOS icon: icons/ios/back-24.pdf ?

**Comment by shorlander** [comment]
> It looks like this is adding one iOS icon: icons/ios/back-24.pdf ?

Or maybe not. Not sure why it's listed as a changed file though.

**Pull request merged**
