### PR TITLE
Fix desktop Redo icon

### PR DESCRIPTION
**Pull request by ExE-Boss**
This fixes the desktop Redo icon.

### CODE REVIEW

**Comment by aminalhazwani** [comment]
Thanks @ExE-Boss, this is being fix with #19.

**Comment by ExE-Boss** [comment]
Given that #19 is taking a long time, can this therefore be reconsidered for merging?

**Comment by aminalhazwani** [comment]
Sorry @ExE-Boss, just merged the PR. As soon as we release the NPM it should be avaiable to the website.

**Comment by ExE-Boss** [comment]
That’s fine, I wasn’t expecting for it to get merged today given how long it took for it to get merged.

**Pull request closed without merging**
